"""
Build Word (.docx) deliverables for the Complex Spine Surgery Cohort analysis.

Mirrors the layout of the original Univariate Tables.docx and
Multivariate Table.docx the user provided.
"""

from __future__ import annotations

from io import BytesIO

import pandas as pd
from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.shared import Pt, RGBColor


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _set_cell_text(cell, text, bold=False, size=10):
    cell.text = ""
    para = cell.paragraphs[0]
    run = para.add_run(text)
    run.font.size = Pt(size)
    run.bold = bold


def _star_p(p_str: str) -> str:
    """Append * to p < 0.05 like the example tables."""
    if not p_str:
        return ""
    if p_str.startswith("<"):
        return p_str + "*"
    try:
        if float(p_str) < 0.05:
            return p_str + "*"
    except Exception:
        pass
    return p_str


def _collapse_levels(rows: list[dict], col0: str, col1: str) -> list[dict]:
    """Collapse multi-level categorical rows into one row (matches R Word style)."""
    out: list[dict] = []
    i = 0
    while i < len(rows):
        r = rows[i]
        if r.get("_type") == "categorical" and r.get("Level"):
            # gather all rows with same Variable
            block = [r]
            j = i + 1
            while j < len(rows) and rows[j].get("Variable") == r["Variable"]:
                block.append(rows[j])
                j += 1

            # Heuristic: if exactly two levels labelled "0" and "1", show only "1"
            # (binary yes/no). Otherwise list every level.
            levels = [b["Level"] for b in block]
            if set(levels) == {"0", "1"}:
                yes_row = next(b for b in block if b["Level"] == "1")
                out.append({
                    "label": r["Variable"],
                    "g0": yes_row[col0],
                    "g1": yes_row[col1],
                    "p": _star_p(r["p-value"]),
                })
            else:
                label_lines = [r["Variable"]] + [f"     {b['Level']}" for b in block]
                g0_lines = [""] + [b[col0] for b in block]
                g1_lines = [""] + [b[col1] for b in block]
                out.append({
                    "label": "\n".join(label_lines),
                    "g0": "\n".join(g0_lines),
                    "g1": "\n".join(g1_lines),
                    "p": _star_p(r["p-value"]),
                })
            i = j
        else:
            out.append({
                "label": r["Variable"],
                "g0": r[col0],
                "g1": r[col1],
                "p": _star_p(r["p-value"]),
            })
            i += 1
    return out


def _add_styled_table(doc, header_row, rows, title=None, footer=None):
    """Add a clean Word table."""
    if title:
        p = doc.add_paragraph()
        run = p.add_run(title)
        run.bold = True
        run.font.size = Pt(11)

    n_cols = len(header_row)
    table = doc.add_table(rows=1 + len(rows), cols=n_cols)
    table.style = "Light Grid Accent 1"

    for c, txt in enumerate(header_row):
        _set_cell_text(table.rows[0].cells[c], txt, bold=True, size=10)

    for r_i, row in enumerate(rows, start=1):
        for c_i, txt in enumerate(row):
            _set_cell_text(table.rows[r_i].cells[c_i], str(txt), size=10)

    if footer:
        p = doc.add_paragraph()
        run = p.add_run(footer)
        run.italic = True
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Public: build the full report
# ---------------------------------------------------------------------------
def build_report_docx(
    *,
    table1_df: pd.DataFrame,
    table2_df: pd.DataFrame,
    multivariate_df: pd.DataFrame,
    sensitivity_results: dict | None,
    mdd: dict | None,
    figure_png_bytes: bytes | None,
    mme_distribution_png_bytes: bytes | None = None,
    group0_label: str,
    group1_label: str,
    pretty_labels: dict | None = None,
    n_group0: int = 0,
    n_group1: int = 0,
) -> bytes:
    """Assemble a single Word document containing every output."""
    doc = Document()
    pretty_labels = pretty_labels or {}

    # ---- Cover ----
    h = doc.add_heading("Complex Spine Surgery Cohort — Analysis Report", level=0)
    p = doc.add_paragraph()
    run = p.add_run(
        "Auto-generated by the Complex Spine Surgery Cohort Analysis App. All "
        "tables and figures were produced from the uploaded dataset using the "
        "same statistical methods as the original R analysis pipeline."
    )
    run.italic = True
    doc.add_paragraph()

    # Helper to apply pretty labels
    def relabel(rows_in):
        out = []
        for r in rows_in:
            r2 = dict(r)
            if r2["_type"] == "categorical" and not r2.get("Level"):
                r2["Variable"] = pretty_labels.get(r2["Variable"], r2["Variable"])
            elif r2["_type"] == "categorical":
                r2["Variable"] = pretty_labels.get(r2["Variable"], r2["Variable"])
            else:
                r2["Variable"] = pretty_labels.get(r2["Variable"], r2["Variable"])
            out.append(r2)
        return out

    # ---- Table 1 ----
    if table1_df is not None and len(table1_df):
        rows = relabel(table1_df.to_dict("records"))
        collapsed = _collapse_levels(rows, group0_label, group1_label)
        word_rows = [
            [r["label"], r["g1"], r["g0"], r["p"]] for r in collapsed
        ]
        _add_styled_table(
            doc,
            header_row=[
                "Variable",
                f"{group1_label} (n={n_group1})",
                f"{group0_label} (n={n_group0})",
                "p-value",
            ],
            rows=word_rows,
            title="Table 1. Baseline Patient and Surgical Characteristics by Group",
            footer=(
                "Continuous variables tested for normality with Shapiro-Wilk. "
                "Normal: Welch t-test (mean ± SD). Non-normal: Mann-Whitney U "
                "(median [IQR]). Categorical: Chi-square or Fisher's exact "
                "(2×2 with any expected cell <5). * p < 0.05."
            ),
        )

    # ---- Table 2 ----
    if table2_df is not None and len(table2_df):
        rows = relabel(table2_df.to_dict("records"))
        collapsed = _collapse_levels(rows, group0_label, group1_label)
        word_rows = [
            [r["label"], r["g1"], r["g0"], r["p"]] for r in collapsed
        ]
        _add_styled_table(
            doc,
            header_row=[
                "Variable",
                f"{group1_label} (n={n_group1})",
                f"{group0_label} (n={n_group0})",
                "p-value",
            ],
            rows=word_rows,
            title="Table 2. Perioperative Data by Group",
            footer=(
                "Statistical testing as in Table 1. * p < 0.05."
            ),
        )

    # ---- Table 3: Multivariate ----
    if sensitivity_results is not None:
        # side-by-side primary vs sensitivity
        sxs = sensitivity_results["side_by_side"]
        primary_label = sensitivity_results["primary_label"]
        sens_label = sensitivity_results["sensitivity_label"]

        header = ["Outcome",
                  f"{primary_label} β (95% CI)", f"{primary_label} p",
                  f"{sens_label} β (95% CI)", f"{sens_label} p"]
        word_rows = []
        for _, r in sxs.iterrows():
            outcome_pretty = pretty_labels.get(r["Outcome"], r["Outcome"])
            word_rows.append([
                outcome_pretty,
                r[f"{primary_label}: β (95% CI)"],
                _star_p(r[f"{primary_label}: p-value"]),
                r[f"{sens_label}: β (95% CI)"],
                _star_p(r[f"{sens_label}: p-value"]),
            ])
        _add_styled_table(
            doc, header_row=header, rows=word_rows,
            title="Table 3. Multivariate Linear Regression — Primary vs Sensitivity",
            footer="Models adjusted for levels involved, duration of surgery, "
                   "and ASA class. * p < 0.05.",
        )

        # Stability
        stab = sensitivity_results["stability"]
        word_rows = [
            [pretty_labels.get(r["Outcome"], r["Outcome"]),
             r["β primary"], r["β sensitivity"],
             r["% change"], r["Stable (≤20% change)"]]
            for _, r in stab.iterrows()
        ]
        _add_styled_table(
            doc,
            header_row=["Outcome", "β primary", "β sensitivity",
                        "% change", "Stable (≤20%)"],
            rows=word_rows,
            title="Table 3b. Beta-coefficient stability check",
        )
    elif multivariate_df is not None and len(multivariate_df):
        word_rows = []
        for _, r in multivariate_df.iterrows():
            outcome_pretty = pretty_labels.get(r["Outcome"], r["Outcome"])
            word_rows.append([
                outcome_pretty,
                r["Estimate (95% CI)"],
                _star_p(r["p-value"]),
            ])
        _add_styled_table(
            doc,
            header_row=["Outcome", "β (95% CI)", "p-value"],
            rows=word_rows,
            title="Table 3. Multivariate Linear Regression",
            footer="Models adjusted for levels involved, duration of surgery, "
                   "and ASA class. * p < 0.05.",
        )

    # ---- MME distribution figure ----
    if mme_distribution_png_bytes is not None:
        doc.add_paragraph()
        p = doc.add_paragraph()
        run = p.add_run(
            f"Figure 1. MME distribution by exposure group "
            f"({group1_label} vs {group0_label})"
        )
        run.bold = True
        run.font.size = Pt(11)
        doc.add_picture(BytesIO(mme_distribution_png_bytes), width=None)
        cap = doc.add_paragraph()
        run = cap.add_run(
            "Each dot represents one patient. Horizontal jitter is cosmetic. "
            "Short horizontal bars indicate the group median. P-values from "
            "Mann-Whitney U test."
        )
        run.italic = True

    # ---- MDD figure ----
    if figure_png_bytes is not None:
        doc.add_paragraph()
        p = doc.add_paragraph()
        fig_num = 2 if mme_distribution_png_bytes is not None else 1
        run = p.add_run(f"Figure {fig_num}. Power vs. Detectable Difference")
        run.bold = True
        run.font.size = Pt(11)
        doc.add_picture(BytesIO(figure_png_bytes), width=None)
        if mdd:
            cap = doc.add_paragraph()
            run = cap.add_run(
                f"Pooled SD = {mdd['pooled_sd']:.1f} {mdd.get('unit', '')}. "
                f"MDD at 80% power = {mdd['mdd_80']:.1f}; "
                f"MDD at 90% power = {mdd['mdd_90']:.1f}. "
                f"Observed difference = {mdd['observed_diff']:.1f}."
            )
            run.italic = True
            run.font.size = Pt(9)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def df_to_docx_bytes(df: pd.DataFrame, title: str = "") -> bytes:
    """Single-table Word export (used for individual download buttons)."""
    doc = Document()
    if title:
        p = doc.add_paragraph()
        run = p.add_run(title)
        run.bold = True
        run.font.size = Pt(12)
    table = doc.add_table(rows=1 + len(df), cols=len(df.columns))
    table.style = "Light Grid Accent 1"
    for c, col in enumerate(df.columns):
        _set_cell_text(table.rows[0].cells[c], str(col), bold=True)
    for r_i, (_, row) in enumerate(df.iterrows(), start=1):
        for c_i, val in enumerate(row):
            _set_cell_text(table.rows[r_i].cells[c_i], str(val))
    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
